# =========================
# JWT & FILE UPLOAD
# =========================
app.jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkeymysecretkey}
app.upload.dir=${UPLOAD_DIR:uploads}

# =========================
# DATABASE CONFIGURATION (CLEVER CLOUD)
# =========================
spring.datasource.url=${DB_URL:jdbc:mysql://b6fahh2nkhy8f4lx0arx-mysql.services.clever-cloud.com:3306/b6fahh2nkhy8f4lx0arx?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:uwn4jlufp6h7fas8}
spring.datasource.password=${DB_PASSWORD:j4UMOzibMpFQYBkICgR3}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# =========================
# SERVER
# =========================
server.port=${PORT:8090}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect