```properties
# =========================
# JWT & FILE UPLOAD
# =========================

app.jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkeymysecretkey}

app.upload.dir=${UPLOAD_DIR:uploads}


# =========================
# DATABASE CONFIGURATION
# =========================

spring.datasource.url=${DB_URL:jdbc:mysql://mysql-394d1ed4-rahulkumbhar9021-10da.j.aivencloud.com:25779/defaultdb?ssl-mode=REQUIRED}

spring.datasource.username=${DB_USERNAME:avnadmin}

spring.datasource.password=${DB_PASSWORD:AVNS_7x4cby6y5Bhjjal4de3}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================
# JPA / HIBERNATE
# =========================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false


# =========================
# SERVER
# =========================

server.port=${PORT:8090}
```
